# foo

arg foo

from foo:443/bar
from localhost/foo
from example.com/foo:bar
from alpine:3.10
from foo/bar
from foo/bar:baz

from hello-world:test as foo
from fooasdf as bar-baz
run [ "foo", "bar", "echo \"hello $world\"" ]
run foo bar baz

ARG image=alpine:3.10
FROM $image

from \
  alpine:3.10 as foo
run ["foo",\
 "bar"\
]

run foo bar baz \
    qux \
    qup

copy \
  --from=foo \
  /foo/bar \
  /foo/baz \
  /qux/

entrypoint foo bar baz
entrypoint ["foo", "bar", "baz"]

cmd foo bar
cmd ["foo", "bar"]

copy foo bar
copy --from=0 /foo /bar

other foo bar
other foo\
 bar

env foo bar baz \
  qux
env foo=bar baz=qux
env zxcv asdf

env foo="bar zxcv" baz=qux zxcv="asdf\"qwerty" \
 zxcv=zxcvzxvb

label foo=bar
label foo="bar"
label "foo bar"="baz qux"
label "foo\
  bar"="baz\"\
  qux"


foo bar
