# (c) Copyright 2024 Hewlett Packard Enterprise Development LP

name: Release

on:
  release:
    types: [created]

jobs:
  upload_artifacts:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Update Tag
        shell: bash
        run: |
          version=$(echo "$GITHUB_REF" | sed 's/refs\/tags\/v//')
          sed -i "s/version = \"0.1.0\"/version = \"$version\"/" Cargo.toml
      - name: Cargo Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish
        run: cargo publish --allow-dirty --locked
