# (c) Copyright 2024 Hewlett Packard Enterprise Development LP

name: Rust Checks

on:
  pull_request:

jobs:
  build:
    name: Rust Checks
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      #TODO fix formatting in a separate pr after moving to actions
      # - name: Rust Format
      #   run: cargo fmt --check
      - name: Clippy
        run: cargo clippy
      - name: Test
        run: cargo test --verbose
